lazarsoma-FTS-2
green-fox-academy/timestone-levelup pull request #14
Opened 2019-07-08 12:38 UTC by lazarsoma

2019-07-08 14:59 UTC, rozanagy reviewed
pls do the needful

2019-07-08 14:59 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/configuration/CustomAuthenticationFailureHandler.java
> +}
EL EOF (empty line, end of file)

2019-07-08 14:59 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/configuration/SecurityConfig.java
> +}
EL EOF <3

2019-07-10 12:07 UTC, drexeverest requested changes

2019-07-10 12:07 UTC, Suviii commented on src/main/java/com/greenfoxacademy/levelup/configuration/CustomAuthenticationFailureHandler.java
> +    String jsonPayload = "{\"message\" : \"%s\", \"timestamp\" : \"%s\" }";
Timestamp was not requested by the user story, but it's okey

2019-07-11 07:21 UTC, drexeverest submitted a review, later dismissed

2019-07-11 07:46 UTC, rozanagy submitted a review, later dismissed

2019-07-15 12:25 UTC, rozanagy approved these changes
ok

2019-07-15 13:52 UTC, drexeverest submitted a review, later dismissed

2019-07-15 14:53 UTC, rozanagy submitted a review, later dismissed

2019-07-15 14:59 UTC, hulfyback submitted a review, later dismissed

2019-07-16 09:46 UTC, rozanagy approved these changes
ok

2019-07-16 10:27 UTC, hulfyback approved these changes

2019-07-16 10:28 UTC, merged