@PostMapping("/api/pitch")  endpoint
green-fox-academy/timestone-levelup pull request #2
Opened 2019-06-25 13:10 UTC by hulfyback

I've written this endpoint and I've made 3 tests:
- status code 201
- status code 401
- status code 404

2019-06-26 10:14 UTC, drexeverest requested changes

2019-06-26 10:14 UTC, Suviii commented on src/main/java/com/greenfoxacademy/levelup/controller/IPitchRestInterface.java
> +  static final String PITCH_REQUIRED_BODY = "{\n"
Collection of static strings would be better if placed in a separate class, or well, in a class instead of an interface

2019-06-26 10:14 UTC, Suviii commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +  public static void setAuthorization(boolean authorized) {
This method is not used

2019-06-26 10:14 UTC, Suviii commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +  public static void setMissingFields(boolean missingField) {
It's not used either

2019-06-26 10:14 UTC, Suviii commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +    httpHeaders.set("Authorization", "");
You are setting the header by yourself instead of checking the incoming header, which would be the point of it

2019-06-26 10:14 UTC, Suviii commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +    } else if (isMissingField) {
isAuthorized/isMissingField are the values of the boolean variables, please put some logic behind them e.g.
 - check for the header
 - check for the fields

2019-06-26 10:14 UTC, Suviii commented on src/test/java/com/greenfoxacademy/levelup/controller_test/PitchRestControllerTest.java
> +  public void whenStatusIsUnauthorized_thenReturnsStatusCode401() throws Exception {
If you have the method to check the header, then you can include an Authorization header here in the test too, so it can be tested like that

2019-06-26 10:14 UTC, Suviii commented on src/test/java/com/greenfoxacademy/levelup/controller_test/PitchRestControllerTest.java
> +  public void whenMissingField_thenReturnsStatusCode404() throws Exception {
If your field checker method is done, than you do not nave to set boolean values here, just put the object in the body which has missing fields, and test it like that

2019-06-28 14:10 UTC, rozanagy reviewed
i am ok with the changes

2019-06-28 14:10 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +  public ResponseEntity<String> postPitchApi(@RequestHeader(value = "Authorization", required = false) String authorization, @RequestBody(required = false) Pitch pitch) throws IllegalAccessException
ok

2019-06-28 14:10 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/model/Pitch.java
> +  public boolean hasNullField() throws IllegalAccessException {
ok

2019-06-28 14:10 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +    } else if (pitch.hasNullField() == true) {
ok

2019-06-28 14:19 UTC, rozanagy reviewed
please make the necessary changes

2019-06-28 14:19 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/IPitchRestInterface.java
> +  public static String PITCH_REQUIRED_BODY = "{\n"
refactor the field name (as not constant anymore)

2019-06-28 14:19 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/IPitchRestInterface.java
> +  public static String PITCH_SUCCESSFUL_BODY = "{\n"
refactor the field name (as not constant anymore)

2019-06-28 14:19 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/IPitchRestInterface.java
> +  public static String PITCH_UNAUTHORIZED_BODY = "{\n"
refactor the field name (as not constant anymore)

2019-06-28 14:19 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/IPitchRestInterface.java
> +  public static String PITCH_UNSUCCESFUL_BODY = "{\n"
refactor the field name (as not constant anymore)

2019-06-28 14:19 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +    if (authorization == null || authorization.equals("")) {
ok (already refactored)

2019-06-28 14:19 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/controller/PitchRestController.java
> +    return new ResponseEntity<>(IPitchRestInterface.PITCH_SUCCESSFUL_BODY,
ok

2019-06-28 14:19 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/model/Pitch.java
> +  public Pitch() {
ok

2019-06-28 14:19 UTC, rozanagy commented on src/test/java/com/greenfoxacademy/levelup/controller_test/PitchRestControllerTest.java
> +            .header("Authorization", "author")
ok

2019-06-28 14:19 UTC, rozanagy commented on src/test/java/com/greenfoxacademy/levelup/controller_test/PitchRestControllerTest.java
> +            .contentType(MediaType.APPLICATION_JSON)
ok

2019-06-28 14:19 UTC, rozanagy commented on src/test/java/com/greenfoxacademy/levelup/controller_test/PitchRestControllerTest.java
> +    String requiredBody = "{\n"
ok

2019-07-01 13:51 UTC, merged