lazarsoma-FTS-28
green-fox-academy/timestone-levelup pull request #20
Opened 2019-07-19 10:55 UTC by lazarsoma

Generate JWT-Token:
GenerateToken class
TokenRestController class
Dependencies

2019-07-31 13:30 UTC, bekobarna submitted a review, later dismissed

2019-07-31 14:44 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/controller/TokenRestController.java
> +
unnecessary empty line

2019-07-31 14:45 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +}
empty line at end of file

2019-07-31 14:47 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +    long ttlMillis = 3600000; // 1 hour
what is ttlMillis? incorrect variable name

2019-07-31 14:48 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +    long expMillis = nowMillis + ttlMillis;
please use a more expressice variable name instead of expMillis and exp

2019-07-31 14:49 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +
unnecessary empty line

2019-07-31 14:49 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +
unnecessary empty line

2019-07-31 14:52 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +public class GenerateToken {
the name of this class is more like a method name, I think it would be a better practice to use a noun for example instead of this

2019-07-31 14:52 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +
doesn't need an empty line here, I think so

2019-07-31 14:54 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/utility/GenerateToken.java
> +}
I've found mostly just some style issue, and that's it

2019-07-31 14:58 UTC, hulfyback requested changes
after you address these minor issues in your code, I will approve it :slightly_smiling_face:

2019-08-05 09:14 UTC, hulfyback submitted a review, later dismissed

2019-08-05 09:22 UTC, rozanagy requested changes
comments, otherwise ok

2019-08-05 09:22 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/model/Pitch.java
>        List<String> holders) {
kommentet pls töröld

2019-08-05 09:22 UTC, rozanagy commented on src/main/java/com/greenfoxacademy/levelup/model/UserDTO.java
> +  /*public UserDTO(User user) {
kommentet pls töröld

2019-08-05 09:25 UTC, rozanagy submitted a review, later dismissed

2019-08-05 09:35 UTC, hulfyback reviewed
delete comments

2019-08-05 09:39 UTC, hulfyback approved these changes
Finally.. :unamused:

2019-08-05 09:41 UTC, rozanagy approved these changes

2019-08-05 09:46 UTC, merged