lazarsoma-FTS-59
green-fox-academy/timestone-levelup pull request #25
Opened 2019-08-06 08:59 UTC by lazarsoma

Create Springfox documentation:

Dependencies
LevelupApplication: EnableSwagger2 annotation and apiDocket method

2019-08-06 10:48 UTC, hulfyback requested changes
almost... :grinning:

2019-08-06 10:48 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/controller/BadgeLibraryController.java
> -import org.springframework.ui.Model;
I've got an error, it's missing this import

2019-08-06 10:48 UTC, hulfyback commented on src/main/java/com/greenfoxacademy/levelup/model/User.java
> +
unnecessary empty line

2019-08-06 11:23 UTC, hulfyback approved these changes
It's OK, I guess :man_shrugging:

2019-08-07 09:04 UTC, drexeverest approved these changes

2019-08-07 10:57 UTC, merged